# Generated by Django 4.1.7 on 2023-04-12 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_exercicio', models.CharField(choices=[('back', 'Back'), ('cardio', 'Cardio'), ('chest', 'Chest'), ('lower_arms', 'Lower Arms'), ('lower_legs', 'Lower Legs'), ('neck', 'Neck'), ('shoulders', 'Shoulders'), ('upper_arms', 'Upper Arms'), ('upper_legs', 'Upper Legs'), ('waist', 'Waist')], max_length=50)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Treinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_treino', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/')),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(choices=[('peitoral', 'Peitoral'), ('costas', 'Costas'), ('perna', 'Perna')], default='', max_length=100)),
            ],
        ),
    ]
