# Generated by Django 4.2 on 2023-04-13 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exercicio',
        ),
    ]
