# Generated by Django 4.1.7 on 2023-04-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='rest',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='exercise',
            name='weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='treinos',
            name='grupo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
