# Generated by Django 4.2 on 2023-04-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_exercise_rest_exercise_weight_treinos_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dormiu', models.IntegerField(default=2)),
                ('acordou', models.IntegerField(default=2)),
            ],
        ),
    ]
