# Generated by Django 4.1.7 on 2023-04-16 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_customuser'),
        ('galeria', '0005_sono'),
    ]

    operations = [
    ]
