# Generated by Django 4.2 on 2023-04-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0007_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='sono',
            name='total_sono',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
