# Generated by Django 4.1.7 on 2023-04-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0008_sono_total_sono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sono',
            name='acordou',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='sono',
            name='dormiu',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='sono',
            name='total_sono',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
