# Generated by Django 4.1.7 on 2023-04-17 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0010_sono_user'),
        ('galeria', '0011_sono_user'),
    ]

    operations = [
    ]
