# Generated by Django 4.1.7 on 2023-04-27 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0012_alter_sono_acordou_alter_sono_dormiu'),
        ('galeria', '0012_merge_0010_sono_user_0011_sono_user'),
    ]

    operations = [
    ]
