# Generated by Django 4.1.7 on 2023-05-03 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('galeria', '0015_exercise_description_exercise_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='treinos',
            name='objetivo',
            field=models.CharField(choices=[('hipertrofia', 'Hipertrofia'), ('resistencia', 'Resistência'), ('forca', 'Força')], default='hipertrofia', max_length=100),
        ),
        migrations.CreateModel(
            name='UserObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_objective', models.CharField(choices=[('hipertrofia', 'Hipertrofia'), ('resistencia', 'Resistência'), ('forca', 'Força')], default='hipertrofia', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
