# Generated by Django 4.2 on 2023-05-07 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0016_horarios'),
        ('galeria', '0017_remove_treinos_objetivo_alter_exercise_rest_and_more'),
    ]

    operations = [
    ]
