# Generated by Django 4.2 on 2023-05-07 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0018_merge_20230506_2116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Horarios',
        ),
    ]
