# Generated by Django 4.1.7 on 2023-05-07 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0019_delete_horarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='planejamento',
            name='data_horario',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
