# Generated by Django 4.2 on 2023-05-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0019_delete_horarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='planejamento',
            name='dia_semana',
            field=models.CharField(default='', max_length=20),
        ),
    ]
