# Generated by Django 4.2 on 2023-05-08 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0020_planejamento_dia_semana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planejamento',
            name='dia_semana',
        ),
    ]
