# Generated by Django 4.2 on 2023-05-09 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0020_planejamento_data_horario_planejamento_dia_semana'),
        ('galeria', '0021_remove_planejamento_dia_semana'),
    ]

    operations = [
    ]
