# Generated by Django 4.2 on 2023-05-09 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0022_merge_20230509_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planejamento',
            name='data_horario',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 9, 10, 52, 26, 569430)),
        ),
    ]
