# Generated by Django 4.1.7 on 2023-05-24 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0032_workout_alter_planejamento_data_horario'),
        ('galeria', '0033_alter_planejamento_data_horario'),
    ]

    operations = [
    ]
