# Generated by Django 4.1.7 on 2023-05-26 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0021_planejamento_dia_semana'),
        ('galeria', '0036_workout_user_alter_planejamento_data_horario'),
    ]

    operations = [
    ]
