# Generated by Django 4.1.7 on 2023-05-26 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0038_planejamento_quantidade_treinos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_treinos', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='planejamento',
            name='quantidade_treinos',
        ),
        migrations.AlterField(
            model_name='planejamento',
            name='data_horario',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 26, 10, 16, 16, 8715)),
        ),
    ]
