# Generated by Django 4.1.7 on 2023-05-26 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0039_historico_remove_planejamento_quantidade_treinos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='quantidade_treinos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='planejamento',
            name='data_horario',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 26, 10, 24, 43, 198652)),
        ),
    ]
