# Generated by Django 4.1.7 on 2023-05-26 13:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('galeria', '0041_historico_user_alter_planejamento_data_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='planejamento',
            name='data_horario',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 26, 10, 37, 18, 91758)),
        ),
    ]
