# Generated by Django 4.1.7 on 2023-06-08 01:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0044_alter_planejamento_data_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='planejamento',
            name='tipo',
            field=models.CharField(choices=[('perna', 'Perna'), ('costas', 'Costas'), ('peito', 'Peito')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planejamento',
            name='data_horario',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 7, 22, 17, 26, 947124)),
        ),
    ]
