# Generated by Django 4.1.7 on 2023-06-09 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0034_planejamento_tipo_alter_exercise_weight_and_more'),
        ('galeria', '0047_customizar_alter_planejamento_data_horario'),
    ]

    operations = [
    ]
