# Generated by Django 4.1.7 on 2023-06-10 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0048_alter_planejamento_data_horario'),
        ('galeria', '0050_planejamento_treinofeito_and_more'),
    ]

    operations = [
    ]
