# Generated by Django 4.2.1 on 2023-06-10 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0050_planejamento_treinofeito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planejamento',
            name='data_horario',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 10, 12, 48, 0, 485659)),
        ),
        migrations.AlterField(
            model_name='sono',
            name='acordou',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='sono',
            name='dormiu',
            field=models.TimeField(default=None),
        ),
    ]
