# Generated by Django 4.1.7 on 2023-06-10 00:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0051_merge_20230609_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planejamento',
            name='data_horario',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 9, 21, 44, 55, 110912)),
        ),
    ]
