# Generated by Django 4.1.7 on 2023-06-11 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0051_alter_planejamento_data_horario_alter_sono_acordou_and_more'),
        ('galeria', '0055_alter_planejamento_data_horario'),
    ]

    operations = [
    ]
